version: "3"

networks:
  whaticket:

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=${MYSQL_ROOT_PASSWORD:-strongpassword}
      - DB_NAME=${MYSQL_DATABASE:-whaticket}
      - JWT_SECRET=${JWT_SECRET:-3123123213123}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-75756756756}
      - BACKEND_URL=https://whaticket-api.atende24h.com.br
      - FRONTEND_URL=https://whaticket-app.atende24h.com.br
      - PROXY_PORT=${PROXY_PORT:-8080}
      - CHROME_ARGS=--no-sandbox --disable-setuid-sandbox
    expose:
      - "3000"
    volumes:
      - ./backend/public/:/usr/src/app/public/
      - ./backend/.wwebjs_auth/:/usr/src/app/.wwebjs_auth/
    networks:
      - whaticket
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      - URL_BACKEND=backend:3000
      - VITE_BACKEND_URL=https://whaticket-api.atende24h.com.br
    expose:
      - "80"
    networks:
      - whaticket
    restart: always

  mysql:
    image: mariadb:10.6
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-whaticket}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-strongpassword}
      - TZ=${TZ:-America/Fortaleza}
    volumes:
      - ./.docker/data/:/var/lib/mysql
    networks:
      - whaticket
    restart: always
